name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  go_router: ^17.1.0
  
  # Supabase & Riverpod Stack
  supabase_flutter: ^2.12.4
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  
  # Persistence & Data
  isar: any
  isar_flutter_libs: any
  path_provider: any
  connectivity_plus: any
  json_annotation: any

  # Animations & FX
  confetti: any
  animated_text_kit: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  
  # Code Generation
  riverpod_generator: any
  isar_generator: any
  build_runner: any
  json_serializable: any

flutter:
  uses-material-design: true
